// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class WV_tbLUsuarios
    {
        public int usua_Id { get; set; }
        public string usua_Usuario { get; set; }
        public string Es_Admin { get; set; }
    }
}