// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class V_Grafico_Paquetes_Por_Cliente
    {
        public string Cliente { get; set; }
        public int? Cantidad { get; set; }
    }
}