// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class WV_tblPaquetes
    {
        public int paqu_Id { get; set; }
        public int paqu_Cliente { get; set; }
        public int paqu_Codigo { get; set; }
        public string Cliente { get; set; }
        public int paqu_Ciudad { get; set; }
        public string ciud_Descri { get; set; }
        public string depa_Descri { get; set; }
        public DateTime? paqu_Bodega { get; set; }
    }
}