// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class tblDepartamentos
    {
        public tblDepartamentos()
        {
            tblCiudades = new HashSet<tblCiudades>();
        }

        public int depa_ID { get; set; }
        public string depa_Descri { get; set; }
        public int depa_UsuarioCrea { get; set; }
        public DateTime? depa_FechaCrea { get; set; }
        public int? depa_UsuarioModifica { get; set; }
        public DateTime? depa_FechaModifica { get; set; }

        public virtual ICollection<tblCiudades> tblCiudades { get; set; }
    }
}