// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class V_ddl_Camiones
    {
        public int cami_Id { get; set; }
        public string Transportista { get; set; }
    }
}