// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class VW_Clientes
    {
        public int pers_Id { get; set; }
        public string cliente { get; set; }
    }
}