// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class WV_tblDepartamentos
    {
        public int depa_ID{ get; set; }
        public string depa_Descri { get; set; }    }
}