// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class tbDepartamentos
    {
        public tbDepartamentos()
        {
            tbCiudades = new HashSet<tbCiudades>();
        }

        public int dep_ID { get; set; }
        public string dep_Descri { get; set; }
        public int dep_UsuarioCrea { get; set; }
        public DateTime? dep_FechaCrea { get; set; }
        public int? dep_UsuarioModifica { get; set; }
        public DateTime? dep_FechaModifica { get; set; }

        public virtual ICollection<tbCiudades> tbCiudades { get; set; }
    }
}