// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class tbEstadoCivil
    {
        public int esta_ID { get; set; }
        public string esta_Descripcion { get; set; }
        public int esta_UsuarioCrea { get; set; }
        public DateTime esta_FechaCrea { get; set; }
        public int? esta_UsuarioModifica { get; set; }
        public DateTime? esta_FechaModifica { get; set; }
    }
}