// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class tblEnvios
    {
        public tblEnvios()
        {
            tblEnviosPorPaquetes = new HashSet<tblEnviosPorPaquetes>();
        }

        public int envi_Id { get; set; }
        public int envi_Camion { get; set; }
        public string envi_FechaSalida { get; set; }
        public int envi_UsuarioCrea { get; set; }
        public DateTime? envi_FechaCrea { get; set; }
        public int? envi_UsuarioModifica { get; set; }
        public DateTime? envi_FechaModifica { get; set; }
        public bool? envi_Estado { get; set; }

        [NotMapped]
        public string Cliente { get; set; }

        [NotMapped]
        public string Cantidad { get; set; }

        public virtual tblCamiones envi_CamionNavigation { get; set; }
        public virtual tblUsuarios envi_UsuarioCreaNavigation { get; set; }
        public virtual tblUsuarios envi_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tblEnviosPorPaquetes> tblEnviosPorPaquetes { get; set; }
    }
}