// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class tblEnviosPorPaquetes
    {
        public int enpa_Id { get; set; }
        public int enpa_Envio { get; set; }
        public int enpa_Paquete { get; set; }
        public int enpa_UsuarioCrea { get; set; }
        public DateTime? enpa_FechaCrea { get; set; }
        public int? enpa_UsuarioModifica { get; set; }
        public DateTime? enpa_FechaModifica { get; set; }
        public bool? enpa_Estado { get; set; }

        [NotMapped]
        public string Cliente { get; set; }

        [NotMapped]
        public string Cantidad { get; set; }

        public virtual tblEnvios enpa_EnvioNavigation { get; set; }
        public virtual tblPaquetes enpa_PaqueteNavigation { get; set; }
        public virtual tblUsuarios enpa_UsuarioCreaNavigation { get; set; }
        public virtual tblUsuarios enpa_UsuarioModificaNavigation { get; set; }
    }
}