// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class tblPaquetes
    {
        public tblPaquetes()
        {
            tblEnviosPorPaquetes = new HashSet<tblEnviosPorPaquetes>();
        }

        public int paqu_Id { get; set; }
        public int paqu_Codigo { get; set; }
        public int paqu_Cliente { get; set; }
        public int paqu_Ciudad { get; set; }
        public string paqu_DireccionExacta { get; set; }
        public string paqu_Observaciones { get; set; }
        public DateTime? paqu_Bodega { get; set; }
        public DateTime? paqu_EnCamino { get; set; }
        public DateTime? paqu_Entregado { get; set; }
        public int paqu_UsuarioCrea { get; set; }
        public DateTime? paqu_FechaCrea { get; set; }
        public int? paqu_UsuarioModifica { get; set; }
        public DateTime? paqu_FechaModifica { get; set; }
        public bool? paqu_Estado { get; set; }

        public virtual tblCiudades paqu_CiudadNavigation { get; set; }
        public virtual tblPersonas paqu_ClienteNavigation { get; set; }
        public virtual tblUsuarios paqu_UsuarioCreaNavigation { get; set; }
        public virtual tblUsuarios paqu_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tblEnviosPorPaquetes> tblEnviosPorPaquetes { get; set; }
    }
}