// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Paqueteria.Entities.Entities
{
    public partial class tblPersonas
    {
        public tblPersonas()
        {
            tblCamiones = new HashSet<tblCamiones>();
            tblPaquetes = new HashSet<tblPaquetes>();
            tblUsuarios = new HashSet<tblUsuarios>();
        }

        public int pers_Id { get; set; }

      
        public string pers_Nombres { get; set; }
        public string pers_Apellidos { get; set; }
        public string pers_DNI { get; set; }
        public bool pers_Puesto { get; set; }
        public string pers_Sexo { get; set; }
        public int pers_EstadoCivil { get; set; }

        public virtual tblEstadoCiviles pers_EstadoCivilNavigation { get; set; }
        public virtual ICollection<tblCamiones> tblCamiones { get; set; }
        public virtual ICollection<tblPaquetes> tblPaquetes { get; set; }
        public virtual ICollection<tblUsuarios> tblUsuarios { get; set; }
    }
}