// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Paqueteria.Entities.Entities;

#nullable disable

namespace Paqueteria.DataAccess.Context
{
    public partial class Db_PaqueteriaContext : DbContext
    {
        public Db_PaqueteriaContext()
        {
        }

        public Db_PaqueteriaContext(DbContextOptions<Db_PaqueteriaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbCiudades> tbCiudades { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEstadoCivil> tbEstadoCivil { get; set; }
        public virtual DbSet<tbEstadoCiviles> tbEstadoCiviles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<tbCiudades>(entity =>
            {
                entity.HasKey(e => e.ciu_ID)
                    .HasName("PK_Gral_tbCiudad_ciu_ID");

                entity.ToTable("tbCiudades", "Gral");

                entity.Property(e => e.ciu_Descri)
                    .IsRequired()
                    .HasMaxLength(150);

                entity.Property(e => e.ciu_FechaCrea)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ciu_FechaModifica).HasColumnType("datetime");

                entity.HasOne(d => d.dep)
                    .WithMany(p => p.tbCiudades)
                    .HasForeignKey(d => d.dep_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Gral_tbCiudad_Gral_tbDepartamento_dep_ID");
            });

            modelBuilder.Entity<tbDepartamentos>(entity =>
            {
                entity.HasKey(e => e.dep_ID)
                    .HasName("PK_Gral_tbDepartamento_dep_ID");

                entity.ToTable("tbDepartamentos", "Gral");

                entity.HasIndex(e => e.dep_Descri, "UQ_Gral_tbDepartamento_dep_Descri")
                    .IsUnique();

                entity.Property(e => e.dep_Descri)
                    .IsRequired()
                    .HasMaxLength(150);

                entity.Property(e => e.dep_FechaCrea)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.dep_FechaModifica).HasColumnType("datetime");
            });

            modelBuilder.Entity<tbEstadoCivil>(entity =>
            {
                entity.HasKey(e => e.esta_ID)
                    .HasName("PK_tbEstadoCivil_esta_ID");

                entity.Property(e => e.esta_Descripcion)
                    .IsRequired()
                    .HasMaxLength(150);

                entity.Property(e => e.esta_FechaCrea).HasColumnType("datetime");

                entity.Property(e => e.esta_FechaModifica).HasColumnType("datetime");
            });

            modelBuilder.Entity<tbEstadoCiviles>(entity =>
            {
                entity.HasKey(e => e.esci_ID)
                    .HasName("PK_Gral_tbEstadoCiviles_esta_ID");

                entity.ToTable("tbEstadoCiviles", "Gral");

                entity.Property(e => e.esci_Descripcion)
                    .IsRequired()
                    .HasMaxLength(150);

                entity.Property(e => e.esci_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.esci_FechaCrea)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.esci_FechaModifica).HasColumnType("datetime");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}